matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      sudo: required
      env: CODECOV_ELIGIBLE=true
before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - brew uninstall swiftlint || true && brew install swiftlint

script:
- ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
